### ISSUE TITLE
minification support?

### ISSUE THREAD

**Issue by andrewstoneameritech** [vishalvisd/react-validator#10]
`Field-Validator t is currently not supported by field-validator,
          Please use fieldValidatorCore.addSupport to add support for the component, For more information please refer to docs`

After compressing it with the UglifyJS webpack plugin, I come across these errors. UglifyJS renames components to characters (as it should). Do you have plans on addressing this? The example above refers to a standard material-ui TextField.

Would love to use this in a production environment. Thanks for your time.

**Comment by vishalvisd** [comment]
A fix that comes to my mind if you are using uglify, then try not to use any internal provided components (viz: TextField, SelectField, DateRangePicker, DatePicker, Select) rather add all the components you are using. In your case, try by adding TextField through 

> fieldValidatorCore.addSupport("TextField",  (args)=>{
>       return args[0].target.value;
>     }, (callback, args)=>{
>       callback(args[0]);
>     }, "errorText")

Please see the readme for the usage

**Comment by vishalvisd** [comment]
with version 4.0.0 - use tagName Prop to provide the tagName of your component in case you use uglify.

> <Validation tagName="TextField" validators={[{
> validator: (v)=>{
> return false;
> },
> errorMessage: "Cannot be empty!"
> }]}>
