### ISSUE TITLE
Working with Material-UI TextField

### ISSUE THREAD

**Issue by designspin** [vishalvisd/react-validator#20]
Hi,

Thanks for the great work on this Validator script.

I'm trying to set this up on a TextField in the latest version of material-ui. The errorText prop seems to of been removed and from what I understand we should be using the error prop and helperText prop to present errors to a user.

I've been able to AddSupport for helperText using fieldValidatorCore, but i'm not sure how I can also set the error prop to true if helperText has content, if that makes sense. fieldValidatorCore only allows you to addSupport for one property correct?

How can I set the boolean error prop based on there being content in my helperText?

**Comment by designspin** [comment]
Okay, I installed the project with NPM but on closer inspection of the source code here I can see it looks like something has been done about helperText already. I'll see if I have the latest version from NPM.

**Comment by vishalvisd** [comment]
setting 'errorPropName' prop to 'error' should work
```

<Validation 
	validators={[
	      {
		validator: (val) => (... your logic for validation),
		errorMessage: "... i guess this you can leave empty as this message will be coming from the helperText props"
	      }
        ]}
       errorPropName='error'>
	<TextField 
	   value={this.state.value}
           helperText={...}
	   onChange={
	    (evt)=>{
	     ...
           }
           ...
         }/>
    </Validation>
```

**Comment by designspin** [comment]
Finally, I have it working! Thanks again.

**Comment by vishalvisd** [comment]
Nice, 
closing the issue

**Comment by vishalvisd** [comment]
> Finally, I have it working! Thanks again.

Please vote your star if you really find it useful.

**Comment by designspin** [comment]
It is useful, thanks again, star added no problem 👍

**Comment by conyakdevelopment** [comment]
I am having a similar issue with a TextField, the validation seems to work (field turns red, cannot submit) but no error message is shown no matter what I try, do you need to add a div to hold the error message? I cannot see this on any example

**Comment by vishalvisd** [comment]
Please share the UI library you're using and its version

**Comment by braytonstafford** [comment]
I ran into a similar issue with Material-UI v4.3.3 and TextField, it turns out in addition to setting 'errorPropName' prop to 'error' you can also provide 'helperPropName' prop as 'helperText' and that will display the validation error below the TextField.

[Pull request](https://github.com/vishalvisd/react-validator/pull/23) to update the documentation and example
