### ISSUE TITLE
Latest code for helperText on MUInot deployed to npm ?? 

### ISSUE THREAD

**Issue by JaydeeSale** [vishalvisd/react-validator#21]
could you deploy the latest code to npm, the helperText fields arent working , and i see a changeset for the new fields are in just not deployed

**Comment by vishalvisd** [comment]
Thanks for pointing this out.
Latest: 5.1.0 published to NPM.

**Comment by vishalvisd** [comment]
Closing this
- feel free to open another issue if your problem isn't resolved
