### ISSUE TITLE
TypeError: Cannot read property 'errorPropName' of undefined

### ISSUE THREAD

**Issue by jawadhaxan007** [vishalvisd/react-validator#22]
Hi, I'm having an issue with build version.
Your validator is working fine in the production version.

This error occurs at this line of build version:

`return _react2.default.createElement("span", null, this.state.childComponentToRender ? this.state.childComponentToRender : "", !getAllSupportedComponent()[this.typeOfCompnent].errorPropName && this.state.isValid === false ? _react2.default.createElement("div", {`

I'm using:
"react": "^16.7.0",
"react-dom": "^16.7.0",
"react-redux": "^5.0.7",
"react-router-dom": "^4.3.1",
"react-scripts": "^2.1.5",
 "redux": "^4.0.0",
 "redux-thunk": "^2.3.0",

"react-validation-framework": "^5.1.0",
"@material-ui/core": "^3.9.2".

I'm using TextField of materialUI.

**Comment by jawadhaxan007** [comment]
componentTag resolved my issue.
Thanks for this great lightweight super library.

**Comment by vireshshah** [comment]
@LeifHorton I am getting exactly same issue. Can you please share your code snippet? I am using material ui 4.9.13 and react 16.13.1.

**Comment by jawadhaxan007** [comment]
@vireshshah I resolved it by initialising TextField of Material ui with custom error props.
I will share the code after sometime.

**Comment by vireshshah** [comment]
Yes please, code would be really helpful. Thanks @LeifHorton .

**Comment by arslanakhtar61** [comment]
I am getting the same error. What is the solution?

**Comment by jawadhaxan007** [comment]
import { fieldValidatorCore } from "react-validation-framework";

fieldValidatorCore.addSupport(
  "TextField",
  args => {
    return args[0].target.value;
  },
  (callback, args) => {
    callback(args[0]);
  },
  "error",
  "helperText"
);

Do this in Index.Js file

**Comment by vireshshah** [comment]
Thanks. I think I did this but it didn't help on that day. I ended up using Formik library.

Thanks for your help though.
