### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'errorPropName')

### ISSUE THREAD

**Issue by ghost** [vishalvisd/react-validator#26]
Getting this error when trying to use it in a functional component:

```
TypeError: Cannot read properties of undefined (reading 'errorPropName')
Validation.render
node_modules/react-validation-framework/index.js:412
  409 | if (this.state.unsupported === true) {
  410 |   return this.props.children;
  411 | } else {
> 412 |   return _react2.default.createElement(
      | ^  413 |     "span",
  414 |     null,
  415 |     this.state.childComponentToRender ? this.state.childComponentToRender : "",
```

PS. this framework looks fantastic, it's a pity is not developed anymore

**Comment by vishalvisd** [comment]
Thanks for mentioning this issue and sorry for the late response. A quick quess is that you might want to use the 'componentTag' prop on the 'Validation' wrapping component. Read the reason on the read me about 'componentTag' prop. I will get back with more information as I relook the code to understand why you might be getting this error.
